### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by razowski** [dmedvinsky/cordova-startapp#2]
Hello,

I'm trying to implement your plugin on Android, but I didn't success for the moment. Is it possible to provide a little small example ?

I would like to start an external application (Autovoice) from my main application (Domotico). If you have 5 minutes to just provide a little example it will be useful.

Thanks 
Xavier

**Comment by dmedvinsky** [comment]
You must know the “path” to the activity you would like to start. Assuming it is

```
com.razowski.Autovoice/com.razowski.Autovoice.MyAutovoiceActivity
```

to start it you should have something like this:

``` html
<html>
  <body>
    <button onclick="go();">Run Autovoice</button>
    <script src="startapp.js"></script>
    <script>
      function go() {
        var win = function() {
          alert('success');
        };
        var fail = function() {
          alert('failed');
        };
        window.startapp.start({ android: 'com.razowski.Autovoice/com.razowski.Autovoice.MyAutovoiceActivity' },
          win, fail);
      }
    </script>
  </body>
</html>
```
